services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=worddee_user
      - POSTGRES_PASSWORD=112233
      - POSTGRES_DB=worddee_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worddee_user -d worddee_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - GEMINI_API_KEY=AIzaSyBn9gp0PYWfNamPX7BpubzJ2FAHmAhiB4Y
      - DATABASE_URL=postgresql://worddee_user:112233@db/worddee_db
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8000

volumes:
  postgres_data: