services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "112233"
      POSTGRES_DB: webwords_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webwords_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_HOST=postgres_db
      - DB_NAME=webwords_db
      - DB_USER=postgres
      - DB_PASS=112233
      - DB_PORT=5432
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: always
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8000

volumes:
  postgres_data: